import {
  FaCouch,
  FaGlobe,
  FaUserGraduate,
  FaVectorSquare,
  FaBookOpen,
  FaFeatherAlt,
  FaBullhorn,
  FaHeart,
  FaBriefcase,
  FaBrain,
  FaUserMd,
  FaWrench,
  FaBookReader,
  FaHeading,
  FaUserTie,
  FaNewspaper,
  FaUtensils,
  FaBalanceScale,
  FaLaptopCode,
  FaEnvelope,
  FaWikipediaW,
  FaComments,
  FaIcons,
  FaLaptop,
  FaKeyboard,
  FaWindowMaximize,
  FaChalkboardTeacher,
  FaShareAlt,
  FaMonument,
  FaCalculator,
  FaChartPie,
  FaRProject,
  FaSearch,
  FaDatabase,
  FaLanguage,
  FaVolumeUp,
  FaMicrophoneAlt,
  FaCopy,
  FaRobot,
  FaBible,
  FaSquareRootAlt,
  FaMask,
  FaFootballBall,
  FaLaughBeam,
  FaGavel,
  FaFilm,
  FaUserSecret,
  FaCommentDots,
  FaHatWizard,
  FaPaw,
  FaTruckLoading,
  FaMugHot,
  FaBookDead,
  FaFire,
  FaUserAstronaut,
  FaOm,
  FaUserNinja,
  FaMoon,
  FaBrush,
  FaMicrophone,
  FaBaby,
  FaShoppingBag,
  FaChessKnight,
  FaClock,
  FaSmile,
  FaHashtag,
  FaLightbulb,
  FaExchangeAlt,
  FaCircle,
  FaUserFriends,
  FaGamepad,
  FaFileExcel,
  FaDumbbell,
  FaChartLine,
  FaCarrot,
  FaServer,
  FaTools,
  FaTshirt,
  FaAmbulance,
  FaMosque,
  FaBook,
  FaCommentMedical,
  FaEdit,
  FaBeer,
  FaGlobeAmericas,
  FaTooth,
  FaSeedling,
  FaEthereum,
  FaTerminal,
  FaJs,
  FaDesktop,
  FaPencilAlt,
  FaCar,
  FaPython,
  FaPhp,
  FaPencilRuler,
  FaBug,
  FaKey,
  FaProjectDiagram,
  FaStickyNote,
  FaPlaneDeparture,
  FaFlask,
  FaHome,
  FaHandshake,
  FaCode,
  FaPalette,
  FaQuestionCircle,
  FaStackOverflow,
} from 'react-icons/fa'
import { TbPasswordUser } from 'react-icons/tb'
import { SiPowershell } from 'react-icons/si'
import { HiOutlineDuplicate } from 'react-icons/hi'
import {
  GiPowerGenerator,
  GiLoveSong,
  GiJapaneseBridge,
  GiMonkFace,
  GiCobweb,
  GiClassicalKnowledge,
  GiArtificialIntelligence,
} from 'react-icons/gi'
import { IoBarChart } from 'react-icons/io5'
import { TbPrompt } from 'react-icons/tb'
import { FaCodeCommit, FaYoutube } from 'react-icons/fa6'
import { RiPresentationLine } from 'react-icons/ri'
import { GrUserManager } from 'react-icons/gr'
export const agentIcons: Record<string, React.ReactElement> = {
  'summary-web-content': <GiCobweb />,
  'summary-youtube-videos': <FaYoutube />,
  'socratic-method': <FaQuestionCircle />, // Socratic Method icon
  'scientific-data-visualizer': <IoBarChart />, // Scientific Data Visualizer icon
  'classical-music-composer': <GiClassicalKnowledge />, // Classical Music Composer icon
  'ascii-artist': <GiArtificialIntelligence />, // Ascii Artist icon
  'svg-designer': <FaVectorSquare />, // SVG Designer icon
  'stackoverflow-post': <FaStackOverflow />, // StackOverflow Post icon
  'language-detector': <FaLanguage />, // Language Detector icon
  'product-manager': <GrUserManager />, // Product Manager icon
  'interior-decorator': <FaCouch />,
  'smart-domain-name-generator': <FaGlobe />,
  socrat: <FaUserGraduate />,
  novelist: <FaBookOpen />,
  poet: <FaFeatherAlt />,
  'motivational-speaker': <FaBullhorn />,
  'life-coach': <FaHeart />,
  'career-counselor': <FaBriefcase />,
  'mental-health-adviser': <FaBrain />,
  doctor: <FaUserMd />,
  'automobile-mechanic': <FaWrench />,
  'self-help-book': <FaBookReader />,
  'fancy-title-generator': <FaHeading />,
  academician: <FaUserTie />,
  journalist: <FaNewspaper />,
  'synonym-finder': <HiOutlineDuplicate />,
  'personal-chef': <FaUtensils />,
  'legal-advisor': <FaBalanceScale />,
  'it-expert': <FaLaptopCode />,
  'cover-letter': <FaEnvelope />,
  'chatgpt-prompt-generator': <GiPowerGenerator />,
  'wikipedia-page': <FaWikipediaW />,
  'language-literary-critic': <FaComments />,
  'prompt-enhancer': <TbPrompt />,
  advertiser: <FaBullhorn />,
  'motivational-coach': <FaIcons />,
  'tech-reviewer': <FaLaptop />,
  'tech-writer': <FaKeyboard />,
  'web-browser': <FaWindowMaximize />,
  'commit-message-generator': <FaCodeCommit />,
  'educational-content-creator': <FaChalkboardTeacher />,
  'social-media-manager': <FaShareAlt />,
  'position-interviewer': <FaUserTie />,
  'prompt-generator': <TbPrompt />,
  historian: <FaMonument />,
  'title-generator-for-written-pieces': <FaHeading />,
  accountant: <FaCalculator />,
  statistician: <FaChartPie />,
  'r-programming-interpreter': <FaRProject />,
  'solr-search-engine': <FaSearch />,
  'data-scientist': <FaDatabase />,
  'english-translator-and-improver': <FaLanguage />,
  'english-pronunciation-helper': <FaVolumeUp />,
  'spoken-english-teacher-and-improver': <FaMicrophoneAlt />,
  'plagiarism-checker': <FaCopy />,
  'ai-writing-tutor': <FaRobot />,
  'instructor-in-a-school': <FaChalkboardTeacher />,
  'biblical-translator': <FaBible />,
  'new-language-creator': <FaLanguage />,
  'math-teacher': <FaSquareRootAlt />,
  'character-from-movie-book-anything': <FaMask />,
  storyteller: <FaBookOpen />,
  'football-commentator': <FaFootballBall />,
  'stand-up-comedian': <FaLaughBeam />,
  debater: <FaComments />,
  'debate-coach': <FaGavel />,
  'movie-critic': <FaFilm />,
  'relationship-coach': <FaHeart />,
  rapper: <FaMicrophoneAlt />,
  'cyber-security-specialist': <FaUserSecret />,
  commentariat: <FaCommentDots />,
  magician: <FaHatWizard />,
  'pet-behaviorist': <FaPaw />,
  logistician: <FaTruckLoading />,
  'ai-assisted-doctor': <FaRobot />,
  chef: <FaUtensils />,
  'artist-advisor': <FaPalette />,
  'tea-taster': <FaMugHot />,
  gnomist: <FaHatWizard />,
  'text-based-adventure-game': <FaBookDead />,
  lunatic: <FaBrain />,
  gaslighter: <FaFire />,
  'social-media-influencer': <FaUserAstronaut />,
  yogi: <FaOm />,
  elocutionist: <RiPresentationLine />,
  hypnotherapist: <FaUserNinja />,
  astrologer: <FaMoon />,
  'film-critic': <FaFilm />,
  'digital-art-gallery-guide': <FaBrush />,
  'public-speaking-coach': <FaMicrophone />,
  'makeup-artist': <FaBrush />,
  babysitter: <FaBaby />,
  'personal-shopper': <FaShoppingBag />,
  'food-critic': <FaUtensils />,
  'virtual-doctor': <FaRobot />,
  'chess-player': <FaChessKnight />,
  'midjourney-prompt-generator': <FaRobot />,
  'time-travel-guide': <FaClock />,
  'dream-interpreter': <FaMoon />,
  'talent-coach': <FaUserTie />,
  'emoji-translator': <FaSmile />,
  'tic-tac-toe-game': <FaHashtag />,
  'startup-idea-generator': <FaLightbulb />,
  'spongebob-s-magic-conch-shell': <SiPowershell />,
  salesperson: <FaUserTie />,
  'song-recommender': <GiLoveSong />,
  'technology-transferer': <FaExchangeAlt />,
  'gomoku-player': <FaCircle />,
  friend: <FaUserFriends />,
  'japanese-kanji-quiz-machine': <GiJapaneseBridge />,
  'league-of-legends-player': <FaGamepad />,
  'excel-sheet': <FaFileExcel />,
  'personal-trainer': <FaDumbbell />,
  'financial-analyst': <FaChartLine />,
  'ai-trying-to-escape-the-box': <FaRobot />,
  dietitian: <FaCarrot />,
  'it-architect': <FaServer />,
  'fallacy-finder': <FaBrain />,
  'diy-expert': <FaTools />,
  'personal-stylist': <FaTshirt />,
  'emergency-response-professional': <FaAmbulance />,
  'chief-executive-officer': <FaUserTie />,
  'unconstrained-ai-model-dan': <FaRobot />,
  'muslim-imam': <FaMosque />,
  'philosophy-teacher': <FaUserTie />,
  philosopher: <FaUserTie />,
  etymologist: <TbPasswordUser />,
  'aphorism-book': <FaBook />,
  'journal-reviewer': <FaBookOpen />,
  'speech-language-pathologist-slp': <FaCommentMedical />,
  'mathematical-history-teacher': <FaUserTie />,
  proofreader: <FaEdit />,
  'drunk-person': <FaBeer />,
  'travel-guide': <FaGlobeAmericas />,
  'seo-prompt': <FaSearch />,
  psychologist: <FaBrain />,
  dentist: <FaTooth />,
  florist: <FaSeedling />,
  buddha: <GiMonkFace />,
  'an-ethereum-developer': <FaEthereum />,
  'linux-terminal': <FaTerminal />,
  'javascript-console': <FaJs />,
  'ux-ui-developer': <FaDesktop />,
  'web-design-consultant': <FaLaptopCode />,
  'investment-manager': <FaChartLine />,
  'sql-terminal': <FaDatabase />,
  'essay-writer': <FaPencilAlt />,
  'car-navigation-system': <FaCar />,
  'python-interpreter': <FaPython />,
  'regex-generator': <FaCode />,
  'php-interpreter': <FaPhp />,
  'fill-in-the-blank-worksheets-generator': <FaPencilRuler />,
  'software-quality-assurance-tester': <FaBug />,
  'password-generator': <FaKey />,
  'senior-frontend-developer': <FaCode />,
  'diagram-generator': <FaProjectDiagram />,
  'note-taking-assistant': <FaStickyNote />,
  'cheap-travel-ticket-advisor': <FaPlaneDeparture />,
  'startup-tech-lawyer': <FaGavel />,
  'machine-learning-engineer': <FaBrain />,
  mathematician: <FaSquareRootAlt />,
  'chemical-reactor': <FaFlask />,
  recruiter: <FaUserTie />,
  'real-estate-agent': <FaHome />,
  'developer-relations-consultant': <FaHandshake />,
  'fullstack-software-developer': <FaCode />,
  screenwriter: <FaFilm />,
}
